'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ConfigProvider } from 'antd';
import theme from './theme/themeConfig';
import { AuthProvider } from './hoc/Context';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <AuthProvider>
        <ConfigProvider theme={theme}>
          <body className={inter.className}>{children}</body>
        </ConfigProvider>
      </AuthProvider>
    </html>
  );
}
